language: node_js
node_js:
- "8"

cache:
  directories:
  - node_modules
  - /usr/local/lib/node_modules

script:
  - npm run build -s
  - npm run test -s

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  - npm run semantic-release
