language: node_js
node_js:
- "node"

cache:
  directories:
  - node_modules
  - /usr/local/lib/node_modules

script:
  - npm run build -s
  - npm run test -s

after_success:
  - npm run semantic-release
